import { Beast, Battle, Bet, LeaderboardEntry, BettorLeaderboardEntry } from '@/lib/types';

export const MOCK_BEASTS: Beast[] = [
  {
    id: 'beast_kong_01',
    ownerAddress: '0x38F2...91C4',
    name: 'APEX MECHA-KONG',
    description: 'Titanium-plated cybernetic primate engineered for raw kinetic impact and crushing offensive brutality.',
    avatarUrl: '/assets/stitch/home/asset_1.jpg',
    stats: { power: 9, defense: 6, speed: 3, special: 2 },
    perks: ['kinetic_overdrive', 'iron_plating'],
    boundAsset: 'BTC',
    record: { wins: 14, losses: 2 },
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'beast_wolf_02',
    ownerAddress: '0x71B0...4E89',
    name: 'FENRIR VECTOR-9',
    description: 'Ultra-high velocity biomechanical wolf specializing in precision critical strikes and synaptic initiative.',
    avatarUrl: '/assets/stitch/home/asset_2.jpg',
    stats: { power: 6, defense: 4, speed: 8, special: 2 },
    perks: ['synaptic_surge', 'predator_instinct'],
    boundAsset: 'ETH',
    record: { wins: 11, losses: 4 },
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'beast_rhino_03',
    ownerAddress: '0x992A...218F',
    name: 'GOLIATH VANGUARD',
    description: 'Impenetrable armored vanguard with heavy sub-dermal shields designed to outlast and grind down agile foes.',
    avatarUrl: '/assets/stitch/home/asset_3.jpg',
    stats: { power: 5, defense: 9, speed: 2, special: 4 },
    perks: ['iron_plating', 'nano_repair'],
    boundAsset: null,
    record: { wins: 8, losses: 5 },
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'beast_panther_04',
    ownerAddress: '0x14C9...8820',
    name: 'SPECTRE NIGHT-STALKER',
    description: 'Stealth-coated hyper-evasive stalker utilizing lightning-fast disruptive strikes.',
    avatarUrl: '/assets/stitch/home/asset_4.jpg',
    stats: { power: 7, defense: 3, speed: 9, special: 1 },
    perks: ['synaptic_surge', 'volt_arc'],
    boundAsset: 'BTC',
    record: { wins: 12, losses: 3 },
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'beast_bear_05',
    ownerAddress: '0x62D1...54A1',
    name: 'URSUS DEMOLISHER',
    description: 'Overclocked seismic devastator wielding high-yield kinetic claws and relentless endurance.',
    avatarUrl: '/assets/stitch/home/asset_5.jpg',
    stats: { power: 8, defense: 7, speed: 3, special: 2 },
    perks: ['kinetic_overdrive', 'nano_repair'],
    boundAsset: 'ETH',
    record: { wins: 9, losses: 6 },
    createdAt: Date.now() - 86400000 * 1,
  },
];

export const MOCK_BATTLES: Battle[] = [
  {
    id: 'battle_live_01',
    beastA: MOCK_BEASTS[0],
    beastB: MOCK_BEASTS[1],
    status: 'live',
    challengeAcceptedAt: Date.now() - 3600000,
    bettingWindowClosesAt: Date.now() - 600000,
    marketPulseA: {
      asset: 'BTC',
      marketId: '0xbtc_15m_live_01',
      symbol: 'BTC-15M-UP',
      intervalSec: 900,
      upProbability: 0.68,
      bestBid: 0.67,
      bestAsk: 0.69,
      modifier: {
        stat: 'power',
        value: 2,
        description: '+2 Power (BTC Bullish Momentum 68%)',
      },
      locked: true,
      oracleQuestionId: '0x9923847291',
      readTimestamp: Date.now() - 600000,
    },
    marketPulseB: {
      asset: 'ETH',
      marketId: '0xeth_15m_live_01',
      symbol: 'ETH-15M-UP',
      intervalSec: 900,
      upProbability: 0.42,
      bestBid: 0.41,
      bestAsk: 0.43,
      modifier: {
        stat: 'speed',
        value: 1,
        description: '+1 Speed (ETH Market Pulse)',
      },
      locked: true,
      oracleQuestionId: '0x8834921011',
      readTimestamp: Date.now() - 600000,
    },
    combatLog: [
      {
        turnNumber: 1,
        actor: 'beastB',
        actionName: 'SYNAPTIC BLITZ',
        reasoning: 'Utilizing opening turn initiative to strike first before Mecha-Kong establishes kinetic posture.',
        damageDealt: 18,
        isCritical: false,
        beastAHp: 82,
        beastBHp: 100,
        combatNarrative: 'Fenrir Vector-9 accelerates instantly across the grid, scoring an early kinetic laceration across Mecha-Kong\'s shoulder plating.',
        timestamp: Date.now() - 180000,
      },
      {
        turnNumber: 2,
        actor: 'beastA',
        actionName: 'SEISMIC SLAM',
        reasoning: 'Countering the agile strike with an area shockwave amplified by the locked BTC +2 Power pulse.',
        damageDealt: 26,
        isCritical: true,
        beastAHp: 82,
        beastBHp: 74,
        combatNarrative: 'Apex Mecha-Kong slams both reinforced fists into the floor; the seismic rupture sends Fenrir Vector-9 crashing into the perimeter barrier.',
        timestamp: Date.now() - 120000,
      },
      {
        turnNumber: 3,
        actor: 'beastB',
        actionName: 'PREDATOR TARGETING',
        reasoning: 'Locking onto fractured armor seam to execute high-efficiency puncturing pass.',
        damageDealt: 21,
        isCritical: false,
        beastAHp: 61,
        beastBHp: 74,
        combatNarrative: 'Fenrir Vector-9 recalibrates optics and lands a clean double-claw puncture into Mecha-Kong\'s cooling conduit.',
        timestamp: Date.now() - 60000,
      },
    ],
    winner: null,
    totalPoolA: 1450,
    totalPoolB: 1220,
    createdAt: Date.now() - 4200000,
  },
  {
    id: 'battle_pending_02',
    beastA: MOCK_BEASTS[3],
    beastB: MOCK_BEASTS[2],
    status: 'pending',
    challengeAcceptedAt: Date.now() - 1200000,
    bettingWindowClosesAt: Date.now() + 2400000, // 40 mins remaining
    marketPulseA: {
      asset: 'BTC',
      marketId: '0xbtc_15m_pending_02',
      symbol: 'BTC-15M-UP',
      intervalSec: 900,
      upProbability: 0.74,
      bestBid: 0.73,
      bestAsk: 0.75,
      modifier: {
        stat: 'speed',
        value: 2,
        description: '+2 Speed (Live BTC Order Book Odds: 74%)',
      },
      locked: false,
      oracleQuestionId: '0x7749102914',
      readTimestamp: Date.now() - 60000,
    },
    marketPulseB: null, // Unbound
    combatLog: [],
    winner: null,
    totalPoolA: 820,
    totalPoolB: 640,
    createdAt: Date.now() - 1200000,
  },
  {
    id: 'battle_completed_03',
    beastA: MOCK_BEASTS[4],
    beastB: MOCK_BEASTS[1],
    status: 'completed',
    challengeAcceptedAt: Date.now() - 86400000,
    bettingWindowClosesAt: Date.now() - 82800000,
    marketPulseA: {
      asset: 'ETH',
      marketId: '0xeth_15m_past',
      symbol: 'ETH-15M-UP',
      intervalSec: 900,
      upProbability: 0.55,
      modifier: {
        stat: 'defense',
        value: 1,
        description: '+1 Defense (ETH Pulse)',
      },
      locked: true,
      readTimestamp: Date.now() - 82800000,
    },
    marketPulseB: {
      asset: 'ETH',
      marketId: '0xeth_15m_past',
      symbol: 'ETH-15M-UP',
      intervalSec: 900,
      upProbability: 0.55,
      modifier: {
        stat: 'speed',
        value: 1,
        description: '+1 Speed (ETH Pulse)',
      },
      locked: true,
      readTimestamp: Date.now() - 82800000,
    },
    combatLog: [
      {
        turnNumber: 1,
        actor: 'beastB',
        actionName: 'KINETIC DASH',
        reasoning: 'Opening strike.',
        damageDealt: 22,
        isCritical: false,
        beastAHp: 78,
        beastBHp: 100,
        combatNarrative: 'Fenrir Vector-9 rushes forward with rapid strikes.',
        timestamp: Date.now() - 82500000,
      },
      {
        turnNumber: 2,
        actor: 'beastA',
        actionName: 'OVERDRIVE CRUSH',
        reasoning: 'Overpowering counter strike.',
        damageDealt: 38,
        isCritical: true,
        beastAHp: 78,
        beastBHp: 62,
        combatNarrative: 'Ursus Demolisher swings an overwhelming heavy smash.',
        timestamp: Date.now() - 82400000,
      },
      {
        turnNumber: 3,
        actor: 'beastA',
        actionName: 'FINISHING BLOW',
        reasoning: 'Decisive blow to conclude fight.',
        damageDealt: 65,
        isCritical: true,
        beastAHp: 78,
        beastBHp: 0,
        combatNarrative: 'Ursus Demolisher executes a fatal takedown, terminating combat.',
        timestamp: Date.now() - 82300000,
      },
    ],
    winner: 'beastA',
    totalPoolA: 2100,
    totalPoolB: 1850,
    createdAt: Date.now() - 86400000,
  },
];

export const MOCK_LEADERBOARD_BEASTS: LeaderboardEntry[] = [
  {
    rank: 1,
    beastId: 'beast_kong_01',
    beastName: 'APEX MECHA-KONG',
    ownerAddress: '0x38F2...91C4',
    avatarUrl: '/assets/stitch/home/asset_1.jpg',
    boundAsset: 'BTC',
    wins: 14,
    losses: 2,
    winRate: 87.5,
    totalBattles: 16,
  },
  {
    rank: 2,
    beastId: 'beast_panther_04',
    beastName: 'SPECTRE NIGHT-STALKER',
    ownerAddress: '0x14C9...8820',
    avatarUrl: '/assets/stitch/home/asset_4.jpg',
    boundAsset: 'BTC',
    wins: 12,
    losses: 3,
    winRate: 80.0,
    totalBattles: 15,
  },
  {
    rank: 3,
    beastId: 'beast_wolf_02',
    beastName: 'FENRIR VECTOR-9',
    ownerAddress: '0x71B0...4E89',
    avatarUrl: '/assets/stitch/home/asset_2.jpg',
    boundAsset: 'ETH',
    wins: 11,
    losses: 4,
    winRate: 73.3,
    totalBattles: 15,
  },
  {
    rank: 4,
    beastId: 'beast_bear_05',
    beastName: 'URSUS DEMOLISHER',
    ownerAddress: '0x62D1...54A1',
    avatarUrl: '/assets/stitch/home/asset_5.jpg',
    boundAsset: 'ETH',
    wins: 9,
    losses: 6,
    winRate: 60.0,
    totalBattles: 15,
  },
  {
    rank: 5,
    beastId: 'beast_rhino_03',
    beastName: 'GOLIATH VANGUARD',
    ownerAddress: '0x992A...218F',
    avatarUrl: '/assets/stitch/home/asset_3.jpg',
    boundAsset: null,
    wins: 8,
    losses: 5,
    winRate: 61.5,
    totalBattles: 13,
  },
];

export const MOCK_LEADERBOARD_BETTORS: BettorLeaderboardEntry[] = [
  {
    rank: 1,
    address: '0x4981...AF23',
    totalWagered: 14200,
    profit: 5840,
    winRate: 78.4,
    totalBets: 37,
  },
  {
    rank: 2,
    address: '0x8892...11D0',
    totalWagered: 11500,
    profit: 4120,
    winRate: 72.1,
    totalBets: 28,
  },
  {
    rank: 3,
    address: '0x221F...99CB',
    totalWagered: 8900,
    profit: 3250,
    winRate: 68.8,
    totalBets: 32,
  },
  {
    rank: 4,
    address: '0x718B...0024',
    totalWagered: 7400,
    profit: 2480,
    winRate: 64.0,
    totalBets: 25,
  },
  {
    rank: 5,
    address: '0x90A1...5E66',
    totalWagered: 6100,
    profit: 1950,
    winRate: 61.9,
    totalBets: 21,
  },
];
